### ISSUE TITLE
Support for linux variants through Homebrew -> Linuxbrew

### ISSUE THREAD

**Issue by qwc** [ericchiang/pup#132]
https://github.com/ericchiang/pup/blob/681d7bb639334bf485476f5872c5bdab10931f9a/pup.rb#L3

Installing pup through linuxbrew on a linux machine retrieves the darwin executable and therefore is unusable.

So there would be some additions needed for linux.x86_64, linux.386, linux.arm, linux.arm64, or simply all platforms you're supporting. 👍

Should be almost a no-brainer for ppl knowing how to "package" for Homebrew.

**Comment by AlJohri** [comment]
This is now fixed: https://github.com/Homebrew/linuxbrew-core/pull/20099

**Comment by SuperSandro2000** [comment]
So this issue can be closed, right?

**Comment by qwc** [comment]
True. :) :+1:
