### ISSUE TITLE
Unable to brew install - arbitrary URL is disabled

### ISSUE THREAD

**Issue by jandolina** [ericchiang/pup#143]
Hey All,
This looks like a great package, but I am having trouble getting started. Can you please verify my command? The response is not encouraging.

`brew install https://raw.githubusercontent.com/EricChiang/pup/master/pup.rb`

`Calling Non-checksummed download of pup formula file from an arbitrary URL is disabled!`

**Comment by gromgit** [comment]
Homebrew disabled installation of arbitrary formula URLs some time back.

**Comment by gromgit** [comment]
And if you're looking for the latest stable release, `brew install pup` will get it for you.

**Comment by jandolina** [comment]
brew install pup
Totally worked! Maybe change the documentation on the main page to say that is how to install it?

Thanks

**Comment by gromgit** [comment]
A PR to do just that was submitted almost 1.5 years ago...and is still open.

**Comment by vinyll** [comment]
As simple as that.
Too bad such a simple solution is not better exposed…
