### ISSUE TITLE
Error with MacOS when using HomeBrew

### ISSUE THREAD

**Issue by ThamognyaKodi** [ericchiang/pup#171]
This is the error message I get when I do `brew install https://raw.githubusercontent.com/EricChiang/pup/master/pup.rb`

```
Error: Non-checksummed download of pup formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.
```

I am not too sure what is wrong since I am not an expert at HomeBew.

**Comment by gromgit** [comment]
Those instructions are **WAY** out of date: https://github.com/ericchiang/pup/issues/166#issuecomment-951976615

You want to just `brew install pup`.

**Comment by ThamognyaKodi** [comment]
Thank you for the solution. It works now.

**Comment by pjasoliya-ontic** [comment]
Can we update the README ? 
Had faced same issue. can subit a PR

**Comment by gromgit** [comment]
Only the repo owner can make the update, and there have been plenty of PRs over the YEARS to adjust the README, all with no response.
