### ISSUE TITLE
streaming implementation request

### ISSUE THREAD

**Issue by zxytim** [ericchiang/pup#22]
when feed html to pup using pipe with infinite streaming content, pup do not output anything but just eat up memory. This behavior restricts pup's use in shell pipe when large input is encountered

**Comment by tokland** [comment]
What I think @zxytim is saying is that it would be great for pup to be pipe-friendly. A simple example:

```
$ ( echo '<p class="p1">contents</p>'; sleep 5 ) | pup 'p text{}'
```

The problem: only when the input process ends (after 5 seconds), pup returns the result. Ideally, it would echo the text right away. 

That's how most UNIX tools work (try the same command with `| grep contents`, for example).
