### ISSUE TITLE
Use several selectors?

### ISSUE THREAD

**Issue by egalion** [ericchiang/pup#27]
Hello, is it possible to use several selectors one after the other. For example from here:

http://voxeu.org/article/economics-secession

I can get separately h1, .article-teaser, article-content

with 

curl hIttp://voxeu.org/article/economics-secession | ./pup 'h1 text{}'

and so on, but I would like the text to appear one after the other. That is, the text from h1, then the text from .article-teaser, and then the text from .article-content.

**Comment by elig0n** [comment]
I was wondering if I could run pup with several selectors but have the results appear in combined order. i.e. group each selector result together: selector1-result1,selector2-result1,selector3-result1, selector1-result2,selector2-result2,selector3-result2, and so on.
