### ISSUE TITLE
Unrecognized flag '--number'

### ISSUE THREAD

**Issue by dannguyen** [EricChiang/pup#31]
On version 0.3.7 (and Ubuntu 14.04, if that matters):

```sh
   curl -s http://example.com | pup --number 'p'
  Unrecognized flag '--number'
  (23) Failed writing body
```

**Comment by Dashed** [comment]
Seems to be removed in v0.3.4 during a rewrite.

**Comment by EricChiang** [comment]
Sorry about that, I'll add that back in for the next release.

**Comment by EricChiang** [comment]
This has been added back in

**Comment by Dashed** [comment]
Thanks! :+1:
