### ISSUE TITLE
Preformatted text gets messed up

### ISSUE THREAD

**Issue by panicbit** [ericchiang/pup#33]
Prettification and indentation by pup messes up preformatted text.

**Comment by EricChiang** [comment]
Do you have a specific example you'd like to see addressed?

**Comment by panicbit** [comment]
I've noticed that this is only an issue if `<pre>` contains tags.
For example:

```html
<pre>
<span>bar</span>
</pre>
```

results in:
```html
<pre>
 <span>
  bar
 </span>
</pre>
```

**Comment by EricChiang** [comment]
Thanks for bringing this up!

It looks like the html parser used in pup (`golang.org/x/net/html`) does a pretty good job of rendering  `<pre>` tags. [[example here](https://gist.github.com/EricChiang/9c74c96473c6cfea50af)]

I'll add this in for the next release.

**Comment by panicbit** [comment]
Thanks :+1:

**Comment by ericchiang** [comment]
`--pre` flag added https://github.com/ericchiang/pup/commit/0b21bd0bc8e08c515e3b739885c08b94a97ea4dc

**Comment by panicbit** [comment]
Nice work! :smiley:

**Comment by ericchiang** [comment]
@panicbit sorry to take so long!

**Comment by panicbit** [comment]
@ericchiang Don't worry, I only needed this feature for a throwaway script (And I could hack around this issue).
