### ISSUE TITLE
Please show me how '+' operator used

### ISSUE THREAD

**Issue by dingmingxin** [ericchiang/pup#34]
I can not understand usage of the '+' operator as wiki said.
pup 'selector + selector'
pup 'div + a' , Is this usage right? but it does not show any results.
Please give more examples. Thank you

**Comment by EricChiang** [comment]
Will add it to the readme when I get a free moment. For now: http://stackoverflow.com/questions/1139763/what-does-the-plus-sign-css-selector-mean
