### ISSUE TITLE
Using Pup as a library/Feature Request

### ISSUE THREAD

**Issue by Immortalin** [ericchiang/pup#37]
Hi, is there a way to use pup as a library? E.g. 

Package main
import ("github.com/ericchiang/pup"
"net/http")

cssSelector :=`...` //CSS selectors
 func main(){
page,err := http.Get(news.ycombinator.com)
result:=Pup.load(page).select(cssSelector)
fmt.Println(result)
}

Apologies for the lack of syntax highlighting and proper formatting as I am typing this on mobile.

Thanks in advance!

**Comment by ericchiang** [comment]
At this moment pup does not expose any of its CSS selection as a package though eventually it might.

pup just uses golang.com/x/net/html to parse HTML. I suggest you is that.

**Comment by ericchiang** [comment]
see #47
