### ISSUE TITLE
Can ":not" only negate simple selector?

### ISSUE THREAD

**Issue by fansgit** [ericchiang/pup#38]
e.g *':not(:first-child)'* will yield parsing error on *pup*.

**Comment by ericchiang** [comment]
Certain pseudo selectors do no allow other pseudo selectors within them

https://developer.mozilla.org/en-US/docs/Web/CSS/:not

> The negation CSS pseudo-class, :not(X), is a functional notation taking a __simple selector X__ as an argument. It matches an element that is not represented by the argument. X must not contain another negation selector.

However this was changed in the latest release: https://github.com/ericchiang/pup/commit/db016ce23c0eb44f510515a0868e44c87eb079e8

If you upgrade pup, you should be fine.

**Comment by fansgit** [comment]
Thanks, it works on *0.3.9* flawlessly!
