### ISSUE TITLE
json{} doesn't decode html entities

### ISSUE THREAD

**Issue by arcanis** [ericchiang/pup#40]
Hi, maybe it would be interesting to automatically decode the html entities when building a json object, don't you think?

ie. that

```html
<div>&amp;</div>
```

would give

```js
{
    "text" : "&",
    ...
}
```

rather than

```js
{
    "text" : "&amp;",
    ...
}
```

Since people will almost always have to convert it anyway (and that `jq` doesn't seem to have any builtin for this :()

**Comment by arcanis** [comment]
Nevermind, I noticed that the `-p` switch does exactly this! Thanks!

**Comment by rzr** [comment]
```
$ jq --version
jq-1.6

$ jq -p
jq: Unknown option -p
```

When was this option introduced ?
