### ISSUE TITLE
json{} is not isomorphic

### ISSUE THREAD

**Issue by arcanis** [ericchiang/pup#41]
This one is a bit troublesome: it's a big issue (I think), but it may break backward compatibility :/

The issue is that pup will return a json array in most cases, except if there is a single element. It's an issue, because it makes it harder to work with the general case (when we don't know how much results we will get). Could it be possible to change this behavior?

**Comment by arcanis** [comment]
In the meantime, or if this issue can't be easily resolved, piping the output to the following command cast the output to an array if it is not. However, it's still an issue when dealing with nested constructs, with no easy answer (except by using this if-then-else check everywhere ...).

```
pup ... | jq 'if . | type == "array" then . else [.] end')"
```

**Comment by ericchiang** [comment]
I'm fine with changing the JSON behavior to always return a list. This can be in the next release.
