### ISSUE TITLE
Binary pup files for all platforms

### ISSUE THREAD

**Issue by glamp** [ericchiang/pup#42]
So I can install on linux server without installing go.

**Comment by ericchiang** [comment]
https://github.com/ericchiang/pup/releases :)

**Comment by kenorb** [comment]
Try:

    install -v -m755 <(curl -sL https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip | gunzip) /usr/local/bin/pup
