### ISSUE TITLE
Does pup supports XML?

### ISSUE THREAD

**Issue by obilodeau** [ericchiang/pup#45]
I'm trying to extract an attribute from a node in this XML (taken from http://www.radio-canada.ca/Medianet/2010/CBF/DeRemarquablesOublies201001210200_m.asx):

```xml
<ASX xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <TITLE>Écoutez la tribune sur François-Xavier Aubry</TITLE>
  <PARAM NAME="isJeunesse" VALUE="False" />
  <PARAM NAME="isVirtualClip" VALUE="False" />
  <ENTRY>
    <REF HREF="http://medias-wm.radio-canada.ca/diffusion/2010/medianet/CBF/DeRemarquablesOublies201001210200_m.wma" />
    <DURATION VALUE="00:55:00.000" />
    <PARAM NAME="ASX" VALUE="http://www.radio-canada.ca/Medianet/2010/CBF/DeRemarquablesOublies201001210200_m.asx" />
    <PARAM NAME="isVideo" VALUE="False" />
    <PARAM NAME="fileType" VALUE="wma" />
    <PARAM NAME="isLive" VALUE="false" />
    <PARAM NAME="emission" VALUE="De remarquables oubliés" />
    <PARAM NAME="chaine" VALUE="CBF" />
    <PARAM NAME="diffusion" VALUE="integral" />
    <PARAM NAME="station" VALUE="Montréal" />
    <STARTTIME VALUE="00:00:00.000" />
  </ENTRY>
```

I couldn't find any means to extract REF's HREF attribute. I tried 'ref attr{href}' and many other things ('entry:first-child attr{href}' comes to mind).

The -c flag works but mangles the DOM a little, which lead me to think that parsing that XML would work fine. Extracting title works.

**Comment by ericchiang** [comment]
Use this: https://github.com/ericchiang/xpup

**Comment by obilodeau** [comment]
Got it to work with:

* xpup: `xpup '/*/ENTRY/REF/@HREF'`
* xpath: `xpath -q -e 'string(/*/ENTRY/REF/@HREF)' 2>/dev/null`

Thanks!
