### ISSUE TITLE
Feature request: line numbers in JSON output

### ISSUE THREAD

**Issue by stephenemslie** [ericchiang/pup#48]
How about adding a `line_number` key to the json object generated the `json{}` display function?

The use-case I have in mind is calling out to pup from vim and loading the results back into into vim's quickfix list to quickly jump between matched lines.

**Comment by ericchiang** [comment]
The line number of the un-parsed HTML?

The HTML parser pup uses ([golang.org/x/net/html](https://godoc.org/golang.org/x/net/html)) doesn't store the original line number of elements. It only builds the parse tree.

**Comment by stephenemslie** [comment]
Yes as you'd need to use the original line number to do something useful with it in the file. It sounds like that doesn't get preserved by the parser though.

**Comment by ericchiang** [comment]
Yep. Seems like a lot of other parsers don't support this feature. I'll update this if x/net/html ever adds that information.
