### ISSUE TITLE
decode html entities when using text{}

### ISSUE THREAD

**Issue by chrisvdb** [ericchiang/pup#50]
Maybe it would make sense to provide an option to decode html entities when using text{} output and thus output &/</... instead of &amp;/&lt/....

I'm now piping the output of pup in 'recode html' which seems to do the trick.

**Comment by ericchiang** [comment]
Is the `-p` flag what you're looking for?

```
$ echo '<a>&lt;a&gt;</a>' | pup a text{}
&lt;a&gt;
$ echo '<a>&lt;a&gt;</a>' | pup -p a text{}
<a>
```

**Comment by chrisvdb** [comment]
That's exactly what I was looking for. It is listed in --help but seems
to be missing from the documentation.

---
