### ISSUE TITLE
import pup in code

### ISSUE THREAD

**Issue by jgranduel** [ericchiang/pup#57]
Hi, 

fairly new to Go, I don't know how to use pup in my code, without relying on pup binary.
(I would like to transform a script using curl to a pure Go solution).

How to call ParseHTML(pupIn, pupCharset) as it's in main package? 

How is it best feasible. Sorry if the question is trivial and if it is more about documentation or packaging as a dependency than a real issue.

Thanks in advance.

**Comment by ericchiang** [comment]
Hi @jgranduel! Questions like this are better suited for [Go general forms](https://golang.org/help/) than developer issues.

You can't import a main package in Go, so you won't be able to import pup.

However pup just uses the [golang.org/x/net/html](https://godoc.org/golang.org/x/net/html) package for parsing HTML. You can easily use that to do all of your HTML parsing.

Here's a program which does what you're describing: https://gist.github.com/ericchiang/4cbefb674c9a4c0b33c2

If you need help understanding the program I posted, please ask for help on the golang-nuts form or the IRC channel (see the link at the top of this comment). They're really nice and that's what they're there for!

**Comment by jgranduel** [comment]
Thank you very much for you answer and the useful Gist.
My question was mainly about using Pup as a library for the ease of use the CSS Selectors. But it'll remain a program. So I'll stick with (and learn) golang.org/x/net/html as you showed in your gist.

Thanks again.

**Comment by ericchiang** [comment]
> My question was mainly about using Pup as a library for the ease of use the CSS Selectors.

see https://godoc.org/github.com/ericchiang/css for experimental support for this

**Comment by john-bonachon** [comment]
Is there any example rendering JSON (using your JSONDisplayer{}) instead of HTML?
