### ISSUE TITLE
String encoding error ?

### ISSUE THREAD

**Issue by TH3Mjuss** [ericchiang/pup#60]
Hi, 

When I download an html file with the following command: `curl -O www.mysite.com/index.html`, I get the following snippet:
```
[...]
<div class="quote">
	“Normal si c'est lent, on est sur le serveur de dev, pas de prod.”
</div>
[...]
```
Now if I want to parse that with pup like `cat index.html | pup 'div[class="quote"] text{}'`, I get the following result: 
`“Normal si c&#39;est lent, on est sur le serveur de dev, pas de prod.”`

Is that normal that a single quote becomes '&#39 ;' ? It also happens with text containing accents.

And if I want to parse my file to get a Json output, I get the following result:
```
{
 "class": "quote",
 "tag": "div",
 "text": "“Normal si c\u0026#39;est lent, on est sur le serveur de dev, pas de prod.”"
}%
```
Now the quote changes from '&#39 ;' to '\u0026#39;'. Is there a way to have a proper encoding for accents, quotes, etc so that I don't get strange character in my files?

Namaste,
 Mehdi

**Comment by jonhoo** [comment]
I wonder if this is related to #55.

**Comment by TH3Mjuss** [comment]
It seems related indeed. I'll switch to the other issue and close that one.
