### ISSUE TITLE
Missing line return after output when using the json{} option

### ISSUE THREAD

**Issue by virtzilla** [ericchiang/pup#62]
When using the json{} option, there is a missing line return after the output in a shell.

Example:
 curl -s https://news.ycombinator.com/item?id=9996333 | pup '.comment json{}'
_.... lots and lots of output ... then these last lines ..._
  "class": "comment",
  "tag": "span"
 }
]**_virtzilla@monstervm:~/Desktop_**

Note the "]" isn't on it's own line on the last line as one would expect. Yes, it's a visual nitpick.

**Comment by ericchiang** [comment]
Fixed. Thanks for the feedback!
