### ISSUE TITLE
Pup gives Trace/breakpoint trap 

### ISSUE THREAD

**Issue by raghvendra-iiita-work** [ericchiang/pup#64]
Using : https://github.com/ericchiang/pup/releases/download/v0.3.9/pup_linux_386.zip

bash-4.2$ curl -s https://news.ycombinator.com/ | pup 'table table tr:nth-last-of-type(n+2) td.title a'
Trace/breakpoint trap

Is it some known issue is someone looking onto this?

**Comment by Ghoughpteighbteau** [comment]
```tylers-laptop@~ $ curl -s https://news.ycombinator.com/ | pup 'table table tr:nth-last-of-type(n+2) td.title a'
<a href="http://electrek.co/2016/05/02/price-solar-power-fell-50-16-months-dubai-0299kwh/">
 The price of solar power just fell 50% in 16 months
</a>
<a href="from?site=electrek.co">
 <span class="sitestr">
  electrek.co
 </span>
</a>
```

```
tylers-laptop@~ $ pup --version
0.3.9
```

can't confirm yet.

**Comment by ericchiang** [comment]
Not seeing this either. Could you try compiling from source and see if that fixes it? Those releases are compiled using a very old version of Go.

**Comment by raghvendra-iiita-work** [comment]
i am using the prebuilt binaries provided by pup. I resorted to using jq instead since i later got hold of some  api's which provided the required content in json also. But i thought to report it anyway. Was an issue in prod for almost a week

**Comment by ericchiang** [comment]
@raghvendra-iiita-work Thanks for the report. I'll do another release of pup with a more up to date version of Go as this seems like an issue with the runtime.

For the meantime could you run `strace` with that version of pup. I'd be interested to see what it's doing.

Also can you confirm that you're on a i386 architecture.

**Comment by ericchiang** [comment]
pup releases have been updated to a more modern version of Go. Going to close this issue for now. Feel free to comment if you'd like me to reopen it.
