### ISSUE TITLE
`import cycle not allowed` when install from Go

### ISSUE THREAD

**Issue by die4live** [ericchiang/pup#66]
I haven't used Go lang before. So after installed to a custom location in Linux, and export `GOROOT` as well as `GOPATH` with my custom path, I got a `import cycle not allowed` error for `go get github.com/ericchiang/pup`, details as follow:

```
import cycle not allowed
package github.com/ericchiang/pup
        imports bytes
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports unsafe
        imports runtime
```

searched but still can't figure out what's the problem.. Anyone helps?

**Comment by ericchiang** [comment]
I believe this has to do with an incorrect GOROOT installation. This error is indicating that there's an import cycle in "runtime", a standard library package that's outside of pup.

Have you followed the Go installation guide and tested the example there?

https://golang.org/doc/install

**Comment by die4live** [comment]
@ericchiang Reset GOROOT to path/to/go instead of path/to/go/bin and installed pup successfully. Thanks a lot!
