### ISSUE TITLE
How to group output of multiple selectors?

### ISSUE THREAD

**Issue by danhawkes** [ericchiang/pup#77]
Given some html like this:
```html
<ul>
  <li>
    <h2>1</h2>
    <div>
      <span class="description">one</span>
    </div>
  </li>
  <li>
    <h2>2</h2>
    <div>
      <span class="description">two</span>
    </div>
  </li>
</ul>
```

I'd like to extract the contents of `h2` and `.description` for each list item. I've tried

`pup 'li h2, li .description'`

which produces

```html
<h2>
 1
</h2>
<h2>
 2
</h2>
<span class="description">
 one
</span>
<span class="description">
 two
</span>
```

However, what I'm after is more of a depth-first grouping of the matching selectors, e.g.:

```html
<h2>
 1
</h2>
<span class="description">
 one
</span>

<h2>
 2
</h2>
<span class="description">
 two
</span>
```

Is this possible?

**Comment by landall** [comment]
I have the same requirement about it...

**Comment by kenorb** [comment]
Related: #59.

**Comment by jiucenglou** [comment]
I wonder whether it is now possible to group output of multiple selectors ?
