### ISSUE TITLE
Result in UTF-8

### ISSUE THREAD

**Issue by lostinroom** [ericchiang/pup#8]
Hi,

Is there any setting to set result in UTF-8?
I execute this command:
curl http://wiki.seg.org/wiki/Dictionary:Deconvolution | pup div#mw-content-text
it gives me some weird characters.
i.e.
(de kon v&#x14d;&#x2019; l&#x16b; sh&#x2202;n) is translated as       â lÅ« shân)<b> kon vÅ
(1995, 285 and 292&#x2013;303) is translated as (1995, 285 and 292â303)

Thanks

**Comment by marcgrue** [comment]
I still have problems with `'`and `&` (and probably more) being converted (I'm on 0.3.8):
```
$ echo "ŷhat & alert('hi')" | pup text{}
ŷhat &amp; alert(&#39;hi&#39;)

$ echo "ŷhat & alert('hi')" | pup text{} --charset utf8
ŷhat &amp; alert(&#39;hi&#39;)
```
Shouldn't the result be this?:
```
ŷhat & alert('hi')
```

And we get double-encoding when outputting json:
```
$ echo "ŷhat & alert('hi')" | pup json{} // same with --charset utf8
{
 "children": [
  {
   "tag": "head"
  },
  {
   "tag": "body",
   "text": "ŷhat \u0026amp; alert(\u0026#39;hi\u0026#39;)"
  }
 ],
 "tag": "html"
}
```
Is there a way to avoid this?

Thanks,
Marc

**Comment by ericchiang** [comment]
By default, pup escapes all HTML. You can use the '-p' or '--plain' to skip that escaping.

```
$ echo "ŷhat & alert('hi')" | pup -p text{}
ŷhat & alert('hi')
```

**Comment by marcgrue** [comment]
Excellent! Thanks for this wonderful tool!
