### ISSUE TITLE
Cannot get <textarea> text{}

### ISSUE THREAD

**Issue by amosbird** [ericchiang/pup#83]
Hi, I'd like to get the 
```
class Solution {
public:
    int maxArea(vector<int>& height) {
        
    }
};
```
from
https://leetcode.com/problems/container-with-most-water/description/  .

I did `curl https://leetcode.com/problems/container-with-most-water/description/ | pup 'textarea text{}'` but it doesn't work.

**Comment by jaraco** [comment]
That's because that URL doesn't have a textarea in it:

```
curl -s https://leetcode.com/problems/container-with-most-water/description/ | grep -i texarea
```

Also produces nothing.

That page has dynamic behaviors that render the content you're seeking. You'll not be able to use curl but will need to load the content with a more robust tool with a Javascript engine.

**Comment by amosbird** [comment]
Thanks!
